language: node_js
node_js: 4
cache:
  directories:
    - node_modules
script: npm test -- --coverage
before_deploy: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
